const ActionTypes = {
  Edit: {
    EDIT_TITLE: 'EDIT_TITLE',
    ADD_QUESTION: 'ADD_QUESTION',
    REMOVE_QUESTION: 'REMOVE_QUESTION',
    ADD_ANSWER: 'ADD_ANSWER',
    REMOVE_ANSWER: 'REMOVE_ANSWER',
    SELECT_CORRECT_ANSWER: 'SELECT_CORRECT_ANSWER',
    SAVE_QUIZ: 'SAVE_QUIZ'
  },
  Answer: {
    CHANGE_ANSWER: 'CHANGE_ANSWER',
    SUBMIT_QUIZ: 'SUBMIT_QUIZ'
  }
}

export default ActionTypes
